import { randomUUID } from 'crypto';

export const createTestOrganization = (overrides?: Record<string, any>) => ({
  id: randomUUID(),
  name: 'Test Organization',
  slug: 'test-org',
  industry: 'AUTO_PARTS',
  baseCurrency: 'MYR',
  timezone: 'Asia/Kuala_Lumpur',
  sstNumber: null,
  businessRegNo: null,
  tin: null,
  email: 'test@example.com',
  phone: null,
  website: null,
  logoUrl: null,
  settings: {},
  address: null,
  status: 'ACTIVE',
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
});

export const createTestUser = (overrides?: Record<string, any>) => ({
  id: randomUUID(),
  email: 'testuser@example.com',
  name: 'Test User',
  passwordHash: 'hashed-password',
  phone: null,
  avatarUrl: null,
  role: 'ADMIN',
  organizationId: randomUUID(),
  preferences: {},
  status: 'ACTIVE',
  lastLoginAt: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
});

export const createTestItem = (overrides?: Record<string, any>) => ({
  id: randomUUID(),
  sku: `SKU-${Date.now()}`,
  name: 'Test Item',
  nameMalay: null,
  description: 'Test item description',
  type: 'INVENTORY',
  unit: 'PCS',
  brand: null,
  partNumber: null,
  crossReferences: [] as string[],
  vehicleModels: [] as string[],
  categoryId: null,
  itemGroupId: null,
  costPrice: 50,
  sellingPrice: 100,
  reorderLevel: 10,
  reorderQty: 50,
  taxable: true,
  taxRateId: null,
  trackInventory: true,
  trackBatches: false,
  trackSerials: false,
  hasCore: false,
  coreCharge: 0,
  coreItemId: null,
  images: [] as string[],
  status: 'ACTIVE',
  organizationId: randomUUID(),
  createdById: null,
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
});

export const createTestWarehouse = (overrides?: Record<string, any>) => ({
  id: randomUUID(),
  name: 'Test Warehouse',
  code: `WH-${Date.now()}`,
  address: null,
  phone: null,
  email: null,
  isDefault: false,
  status: 'ACTIVE',
  organizationId: randomUUID(),
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
});

export const createTestContact = (overrides?: Record<string, any>) => ({
  id: randomUUID(),
  type: 'CUSTOMER',
  companyName: 'Test Company Sdn Bhd',
  displayName: 'Test Company',
  firstName: null,
  lastName: null,
  email: 'contact@test.com',
  phone: '+60123456789',
  mobile: null,
  website: null,
  billingAddress: null,
  shippingAddress: null,
  taxNumber: null,
  creditLimit: 10000,
  paymentTermId: null,
  priceListId: null,
  notes: null,
  status: 'ACTIVE',
  organizationId: randomUUID(),
  createdAt: new Date(),
  updatedAt: new Date(),
  ...overrides,
});

export const createTestStockLevel = (overrides?: Record<string, any>) => ({
  id: randomUUID(),
  itemId: randomUUID(),
  warehouseId: randomUUID(),
  stockOnHand: 100,
  committedStock: 10,
  incomingStock: 0,
  updatedAt: new Date(),
  ...overrides,
});
